burke/zeus

- rubygem/lib/zeus/m.rb
- rubygem/lib/zeus/rails.rb
Attempt to fix currently failing `zeus test (rspec, testrb)` command (#213):
1. `Rake::Task['test']` fails to invoke the `test` task. To fix this, use `Rake::Application` to load the app's Rakefile, and then invoke the `test` task.
2. After fixing the above, `zeus test` on an app using RSpec still does not work as expected because the test command falls through to `Zeus::M`. To fix, invoke the RSpec runner on the following condition: 
1. no arguments are passed in `zeus test`, and
2. `defined?(RSpec) == true`
This means that if RSpec and *other* testing frameworks are in use (#149), `zeus test` will run the RSpec suite by default. To run another framework's suites, the user will have to run `zeus test <path_to_other_suite>`. Hopefully this is reasonable.
> Fix "zeus test"

- rubygem/ext/inotify-wrapper/inotify-wrapper.cpp
on EOF select() says stdin is ready, fgets fails and so inotify-wrapper loops
forever
> inotify-wrapper: don't hang on EOF [fix #501]

- rubygem/Gemfile
- rubygem/lib/zeus/m.rb
- rubygem/lib/zeus/rails.rb
- rubygem/spec/fake_mini_test.rb
- rubygem/spec/m_spec.rb
- rubygem/spec/rails_spec.rb
- rubygem/spec/spec_helper.rb
We want to run Minitest via `Minitest.run`. Rails requires `'minitest/autorun'` when requiring `'rails/test_help'` which means invoking `Minitest.run(our_arguments)` will cause tests to get run twice, once with our arguments and once with ARGV via autorun.
Instead of trying to hack around Minitest class variables and prevent autorun from working, we'll stop fighting it and let Minitest run our desired tests by replacing ARGV with our desired test arguments and letting autorun invoke the tests when the child processes exit. This is still a bit of an introspection of Minitest's API because we're mangling ARGV but Minitest has executed with ARGV explicitly in autorun for at least two major releases so we'll go with it for now.
Previously discussed …
> Remove hacks around Minitest internals, make peace with Minitest.autorun

- rubygem/lib/zeus/load_tracking.rb
- rubygem/spec/load_tracking_spec.rb
1. Check the file if it exists in the `LOAD_PATH` before checking if it
exists locally. If it's in the load path, use that path. If not, check for
it's existence locally.
2. We expand the file path first, which simplifies the checking of the
file's existence in the `LOAD_PATH` or on the file system.
Add some specs for methods in `Zeus::LoadTracking` module.
> Simplify load tracking logic

- rubygem/lib/zeus.rb
- rubygem/lib/zeus/rails.rb
- rubygem/spec/rails_spec.rb
I'm not sure if this has been discussed already. Using the `require
'bundle/setup'` directive made the gem activation errors a bit more
predictable for me during some preliminary runs. It's quite possible
that I might've missed something here.
Adding "require 'bundler/setup'" to a file will add the bundled gems to
the load path. This is a much safer way to load gems instead of using
`gem <gemname>, <version>` where version is parsed from the Gemfile.
Loading 'bundler/setup.rb' does the following things:
1. Cleans load path; one of it's function is to removing system gems
from the load path.
2. Loads the gem specs from Gemfile.lock
3. Sets up the following path variables:
BUNDLE_BIN_PATH
BUNDLE_GEMFILE: location of the Gemfile
PATH: Appends the location of `bundle` executable for the …
> Use bundler/setup instead of custom loading code

- .travis.yml
- Makefile
- go/cmd/zeus/zeus.go
- go/filemonitor/filemonitor.go
- go/unixsocket/unixsocket.go
- go/zeusclient/zeusclient.go
- go/zeusmaster/zeusmaster.go
- go/zeusmaster/zeusmaster_test.go
This adds an end-to-end integration test that:
* Boots Zeus with a tree of multiple commands.
* Ensures that commands boot up.
* Ensures that commands reload when ruby or yaml dependencies change.
The test is currently quite coarse and doesn't introspect much of what Zeus is doing. The goal is to have at least a basic sanity check before writing more detailed unit tests.
I was not able to get rubinius working inside of the Travis golang VM so I've dropped that from the build matrix but retained the other MRI ruby versions.
> End-to-end integration test

- Makefile
Make the VERSION file a dependency of build targets that rely on it. Without this, changing the VERSION file doesn't invalidate things like rubygem/lib/zeus/version.rb that are built from it. This means you can't build a new version without running `make clean`.
> Make the VERSION file a dependency of build targets that rely on it

- go/processtree/slavenode.go
- go/statuschart/stdout.go
- go/statuschart/tty.go
Currently requestRestart accesses the State attribute of the SlaveNode's Slaves without holding a mutex. This PR makes state a private attribute with a public accessor that automatically locks before reading.
In the process I removed the `stateChanged` Cond which appears to be left over from an old version of the code:
https://github.com/burke/zeus/blob/e20fb4ae6a510ec2c0444d991f4ae12db4111212/go/zeusmaster/slavenode.go
Do you have a standard test plan for changes to the Zeus codebase? I'm happy to try merging this into the Stripe fork first and running it here if that's the best approach but I think it'd be nice to upstream.
cc @ptarjan
> Make SlaveNode State access threadsafe

- go/filemonitor/filemonitor_darwin.go
We were correctly checking whether a file was already watched before adding it to our watch list but not correctly marking it as watched. This resulted in some speed and reliability issues on OS X since:
https://github.com/burke/zeus/pull/550
> Fix adding files to filemonitor under OS X

- go/statuschart/statuschart.go
- go/statuschart/stdout.go
- go/statuschart/tty.go
When a single parent node's status changes, it causes a cascade of updates to child nodes. All of those updates report separate `StateChange`s, frequently causing multiple identical lines to be printed. Adding a very small debounce to the update monitoring avoids this noise while hiding only the most ephemeral state transitions.
r? @ptarjan
> Apply a small debounce to status chart updates

- .travis.yml
- Makefile
- go/clienthandler/clienthandler.go
- go/cmd/zeus/zeus.go
- go/messages/messages.go
- go/processtree/processtree.go
- go/processtree/slavemonitor.go
- go/processtree/slavenode.go
- go/statuschart/statuschart.go
- go/zeusclient/zeusclient.go
- go/zeusmaster/zeusmaster_test.go
- rubygem/lib/zeus.rb
We've experienced frequent problems with Zeus nodes getting hung in an Unbooted state. I believe I traced it to a race condition that occurs when a parent reboots while a child is locked booting a command. Before tracking that down, I noticed that there was a decent bit of simplification that could be applied to the state machine that should result in better behavior overall and get rid of this particular bug. See individual commit messages for more details.
Given the subtlety of the concurrent operations here, I intend to roll this out to a handful of developers this week and get them to smoke test it before merging anything.
> Simplify and remove some races from SlaveNode state machine

- .travis.yml
Our filemonitoring code varies by OS but was only being run on Linux in Travis.
> Run Travis build on both OS X and Linux

- rubygem/lib/zeus.rb
- rubygem/lib/zeus/rails.rb
- rubygem/spec/rails_spec.rb
This reverts #530.
The README currently advises [running Zeus outside of bundler](https://github.com/burke/zeus/blob/810c8f49798d4f64b16894abd94beedbddb0b37f/README.md#installation). I agree that running Zeus without bundler is probably a bad tradeoff in terms of stability but I don't think we can change this without
[breaking everyone's Zeus integrations](https://github.com/burke/zeus/issues/570). I believe we should revert until we're prepared to re-introduce this with changes to the README, better error messaging to help people transition and possibly a major version bump.
> Revert #530 (requires using Zeus with bundler)

- rubygem/lib/zeus/load_tracking.rb
`find_in_load_path` was introduced in a very early version of Zeus. It allowed you to pass a path to `add_feature` that is relative to something in the `$LOAD_PATH`, rather than an absolute path.  This made the semantics of `add_feature` equivalent to `require`. ba7c7d7a3018319d86a8c685c72f3476ff75a31f attempted to simplify this logic but actually broke it completely. The current code searches for the file in the `$LOAD_PATH`, which contains a list of directories so no Ruby filename will match. Things in the `$LOAD_PATH` should always exist so it's also duplicative of the `File.exist?` check.
We could roll back ba7c7d7a3018319d86a8c685c72f3476ff75a31f, but since no one has reported an issue, I suspect that code is not being relied on.  That makes some sense since it predates most Zeus …
> Remove find_in_load_path

- .travis.yml
- Makefile
* Use real targets so that Make will correctly handle rebuilding on changes.
* Incorporate linux/darwin logic into the Makefile to avoid duplicate targets that humans need to choose between.
* Remove `dev_bootstrap` so that `make` works out-of-the-box for new developers.
* Create a single `make test` command to run all tests.
> Cleanup Makefile

- go/processtree/slavenode.go
There's a race condition in SlaveNode in which we see a stale child process boot and need to kill it:
* Send a request to boot a child process.
* File change causes us to kill the parent.
* Child boots but is associated with an old parent so we kill it.
This is harmless but currently logs a scary error to STDOUT. We should send this to the trace log instead.
r? @ptarjan
> Do not log unexpected process kills to STDOUT

- .travis.yml
- go/filemonitor/filelistener.go
- go/filemonitor/filelistener_test.go
- go/filemonitor/filemonitor.go
- go/filemonitor/filemonitor_darwin.go
- go/filemonitor/filemonitor_fsnotify.go
- go/filemonitor/filemonitor_test.go
The file monitor fileChangeDelay parameter should act to debounce change events. It should only report an event when it has not seen a new change for at least fileChangeDelay. Currently Zeus implements throttling as opposed to debouncing -- it sends an event at most every fileChangeDelay but does not wait for the event stream to quiesce before sending the first event. This can result in reloading code in the midst of an operation such as an rsync or git change.
> Fix debouncing logic

- go/processtree/processtree.go
- go/processtree/slavemonitor.go
This adds logging for file changes that trigger restarts. It should help with debugging cases where Zeus appeared not to restart correctly. Observed the new log output by running the tests verbosely:
```
...
2016/08/24 17:22:31.188117 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/processtree.go:71] boot/(15743) 2 files changed, beginning with "/private/var/folders/z9/60xl3r5s7y7_z4tr62pyplh00000gn/T/zeus_test054172267/code.rb"
2016/08/24 17:22:31.188156 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/processtree.go:79] data/(15769) restarting for "/private/var/folders/z9/60xl3r5s7y7_z4tr62pyplh00000gn/T/zeus_test054172267/data.yaml"
2016/08/24 17:22:31.188175 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/processtree.go:79] code/(15770) …
```
> Log changed files during restarts

- examples/custom_plan/cucumber_plan.rb
Cucumber seems to run in the development environment with the example plan shown. This PR recommends forcing it to use the test environment for cucumber tests. 
The main reason for this is because many people have `config.cache_classes` set to `false` for development, which prevents cucumber tests from running properly if you also use transactions as a database cleanup strategy (also a very common setting).
> Force test environmnet in custom plans

- vagrant/Gemfile
A gem shouldn't need to mention itself in its Gemfile and this seems to be causing problems with our Travis CI builds.
> Fix Travis by removing excess Gem mention

- go/filemonitor/filelistener.go
- go/filemonitor/filelistener_test.go
- go/filemonitor/filemonitor.go
- go/filemonitor/filemonitor_darwin.go
- go/filemonitor/filemonitor_fsnotify.go
- go/filemonitor/filemonitor_test.go
The new debouncing strategy is still not quite what we want. We really
want to stop all services until changes have stopped and then start them
all again. This change makes things worse by leaving old code running longer.
This reverts commit f1d59a855f69b5afee5d67e71c669ab35cfefefe, reversing
changes made to c55b133d5379c2b14511c67c3dfcfc413b40cf28. Note that I excluded the changes to Travis configuration from the revert.
> Revert "Merge pull request #583 from burke/andrew-debounce-better"

- rubygem/spec/load_tracking_spec.rb
The LoadTracking spec is currently failing for Ruby 2.3+ due to:
https://bugs.ruby-lang.org/issues/12811
This hacks around the VM bug by changing the expectation depending on the running version of Ruby.
> Fix LoadTracking spec for Ruby SyntaxError bug

- go/processtree/slavenode.go
Currently when Zeus receives any error reading from the command socket while waiting for a process to boot, it logs the error and then tries to parse the message anyway. Since the message shouldn't be valid when there's an error, we should instead enter an `SCrashed` state immediately. We could be throwing away useful debugging information bufferred from an earlier read but I don't think that'll actually happen in the existing Zeus code.
> Handle errors reading from socket during boot gracefully

- go/shinylog/shinylog.go
- go/zerror/zerror.go
When zeus has an error it is quite inconvinient to have it written to stdout as
this easily hides problems. To resolve this we allow `shinylog` to log to
`stderr` for strings. As those are user facing error we want to hide the
implementation detail of go so don't log error locations as they are most likely
not helpful to the end user.
fixes #612
> Log zeus error to stderr

- go/clienthandler/clienthandler.go
- go/cmd/zeus/zeus.go
- go/zeusclient/zeusclient.go
- go/zeusmaster/zeusmaster_test.go
- rubygem/lib/zeus.rb
It is often helpful to have seperate streams for stdout and stderr especially
when grepping stdout I still want to see errors on stderr.
> Seperate stdout and stderr

- rubygem/lib/zeus/rails.rb
`zeus rspec` fails for rspec 2 since the invoke method does not exist on RSpec::Core::Runner until rspec 3
* **`uname -a`**: Darwin I.local 15.6.0 Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64
* **`ruby -v`**: 
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
1) `zeus start` in a rails project with rails 2 
2) `zeus rspec`
```
/usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/zeus-0.15.12/lib/zeus/rails.rb:207:in `test': undefined method `invoke' for RSpec::Core::Runner:Class (NoMethodError)
```
* tests run
> re-support rspec 2

- go/filemonitor/filemonitor_darwin.go
- go/filemonitor/filemonitor_test.go
It seems like there is a problem with fsevents when dealing with a large amount
of files on OSX sierra this added test fails reliably on mac Macbook Pro, with
the error
```
2017-01-17 22:52 filemonitor.test[69205] (FSEvents.framework)
FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc()
=> (null) (-22)
```
To test this up the count of files in `filemonitor_test.TestFileMonitorFiles`,
to something like `5000` and the error will show up in the log when running
`make test-go`.
To fix this the proposed quick solution is to on OSX monitor directories instead
of files, when a file is added to the watch list compute the directory it is
contained in and monitor this directory via FSEvents. This can cause more
restarts than before.
fixes #607 #589
> Many files problem on OSX Sierra

- README.md
I installed zeus this afternoon and missed the `zeus init` step and a couple other set up steps that I found [at this Thoughtbot article](https://robots.thoughtbot.com/improving-rails-boot-time-with-zeus). They seemed like they should be included in the README so I added them. 
First open source pull request, sorry in advance if I'm missing something!
> Add a few more essential set up instructions to README

- rubygem/lib/zeus/rails.rb
When running `zeus rspec` without any arguments it seems sensible to expect zeus
to run all the specs, same as `zeus rspec spec`. This behaviour is the same as
`<= 0.15.4`.
Fixes #595
> run rspec specs by default

- emacs/README.md
- emacs/zeus.el
- go/cmd/zeus/zeus.go
- go/processtree/slavenode.go
- go/statuschart/statuschart.go
- go/zeusmaster/zeusmaster.go
- go/zeusmaster/zeusmaster_test.go
The default zeus output requires an advanced terminal and is also hard to parse,
to make integration in emacs etc easier this adds a simple output format like
```
Starting Zeus server v0.15.13
node: boot status: unbooted
node: prerake status: unbooted
node: default_env status: unbooted
node: default_env status: booted
node: boot status: ready
node: prerake status: booted
node: default_env status: ready
node: prerake status: ready
node: default_env status: booted
node: default_env status: ready
node: default_env status: booted
node: default_env status: ready
```
which adds a line for each state change.
> [issue-431] simple status output format

- go/processtree/processtree.go
- go/statuschart/tty.go
On a project with custom commands added, it becomes difficult to find commands in a long list since the commands are shown unsorted. To make things worse, each time I restart Zeus, the commands are shown in a slightly different order, making it particularly hard to find. Our command list is 23 lines long, so you can imagine how tedious it is to be looking for a specific command.
While I would have preferred that commands were shown in groups, split by the environment and then sorted within each group, my Go skills are not yet sufficient for such wizardry.
If this gets accepted, I might look into breaking the command list by environment too :)
> Show commands sorted for consistency & ease of use

- rubygem/lib/zeus/pry.rb
This change allows Zeus to work with both Pry v0.13+ as well as
versions prior to that.
Fixes #674
> Fix compatibility with Pry 0.13+

- examples/custom_plan/zeus.json
- examples/zeus.json
If you **just** installed Zeus, and try running it without `zeus init`, it fails because it cannot require `ubygems`.
The command that is shown in these files has the option `-rubygems` which seems to be missing one `r` (i.e. `-rrubygems`)
> Typo when requiring rubygems in zeus.json example files

- rubygem/lib/zeus/pry.rb
I'm not clear on what is going on, though currently I'm getting errors on the latest version of pry when I try to do anything in a console:
```
(pry) output error: #<NameError: undefined local variable or method `_pry_' for #<Pry::Pager:0x00007fe77e5c8b50>
```
It seems like `pry_instance` is defined as an instance variable when this is run, so `respond_to?` doesn't pick it up. This change to `defined?` will work for instance variables AND method definitions to cover our bases.
> Use defined? instead of respond_to? in Pry monkeypatch

- rubygem/lib/zeus.rb
- rubygem/lib/zeus/pry.rb
- rubygem/lib/zeus/rails.rb
This should help with issue #617 by not incidentally loading pry at whatever the newest (~> 0.10) gem available is before a bundle using an older pry version can be considered.
> Don't require pry; only patch it if it is loaded

- rubygem/lib/zeus/m.rb
- rubygem/lib/zeus/rails.rb
`File.exists?` was aliased to `File.exist?` in versions of Ruby up to 3.1.
`File.exists?` is no longer supported since Ruby 3.2.
> Replacing calls to the alias File.exists? (deprecated since Ruby v3.x) with File.exist?

- rubygem/lib/zeus/m.rb
I noticed that Minitest did not run any tests. 
I added this line to make sure they run instead of just exiting.
> Have Minitest actualy run tests instead of exiting
